/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-13 16:49:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class booking1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"err.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link type='text/css' rel='stylesheet' href='style.css'>\r\n");
      out.write("<table width='100%' height='100%' class='admin' style='border-spacing:20px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=4 align='center'>\r\n");
      out.write("\t\t<a href='cust_home.jsp'><img src='images/users.jpg' width=200 height=200/></a>\r\n");
      out.write("\t\t<h1>Welcome Customer - ");
      out.print(session.getAttribute("cname"));
      out.write("</h1>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event","root","jasper");

	int bno = Integer.parseInt(request.getParameter("bno"));
	String bdate = request.getParameter("bdate");
	String edate = request.getParameter("edate");
	String occ = request.getParameter("occ");
	int vid = Integer.parseInt(request.getParameter("vid"));
	int did = Integer.parseInt(request.getParameter("did"));
	int cid = Integer.parseInt(request.getParameter("cid"));
	int pid = Integer.parseInt(request.getParameter("pid"));
	int nop = Integer.parseInt(request.getParameter("nop"));
	int tid = Integer.parseInt(request.getParameter("tid"));

	PreparedStatement ps = con.prepareStatement("select * from bill where venue_id=? and event_date=? and status='Booked'");
	ps.setInt(1,vid);
	ps.setString(2,edate);

	ResultSet rs = ps.executeQuery();

	if(rs.next()){

      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("alert(\"Venue not available\");\r\n");
      out.write("</script>\r\n");

		return;
	}

	ps = con.prepareStatement("select * from bill where decorator_id=? and event_date=? and status='Booked'");
	ps.setInt(1,did);
	ps.setString(2,edate);

	rs = ps.executeQuery();

	if(rs.next()){

      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("alert(\"Decorator not available\");\r\n");
      out.write("</script>\r\n");

		return;
	}

	ps = con.prepareStatement("select * from bill where caterer_id=? and event_date=? and status='Booked'");
	ps.setInt(1,cid);
	ps.setString(2,edate);

	rs = ps.executeQuery();

	if(rs.next()){

      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("alert(\"Caterer not available\");\r\n");
      out.write("</script>\r\n");

		return;
	}
	
	ps = con.prepareStatement("select * from bill where p_id=? and event_date=? and status='Booked'");
	ps.setInt(1,pid);
	ps.setString(2,edate);

	rs = ps.executeQuery();

	if(rs.next()){

      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("alert(\"Photographer not available\");\r\n");
      out.write("</script>\r\n");

		return;
	}

	ps = con.prepareStatement("select venue_rate from venue where venue_id=?");
	ps.setInt(1,vid);
	rs = ps.executeQuery();
	rs.next();
	float vrate = rs.getFloat(1);

	ps = con.prepareStatement("select decorator_rate from decorator where decorator_id=?");
	ps.setInt(1,did);
	rs = ps.executeQuery();
	rs.next();
	float drate = rs.getFloat(1);

	ps = con.prepareStatement("select p_rate from photographer where p_id=?");
	ps.setInt(1,pid);
	rs = ps.executeQuery();
	rs.next();
	float prate = rs.getFloat(1);
	
	ps = con.prepareStatement("select t_rate from thali where t_id=?");
	ps.setInt(1,tid);
	rs = ps.executeQuery();
	rs.next();
	float food = rs.getFloat(1)*nop;

	float tot = vrate + drate + prate + food;
	float tax = tot * 0.12F;
	float amt = tot + tax;

	ps = con.prepareStatement("insert into bill values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
	ps.setInt(1,bno);
	ps.setString(2,bdate);
	ps.setString(3,edate);
	ps.setString(4,occ);
	ps.setInt(5,vid);
	ps.setInt(6,did);
	ps.setInt(7,cid);
	ps.setInt(8,pid);
	ps.setInt(9,nop);
	ps.setInt(10,tid);
	ps.setFloat(11,amt);
	ps.setString(12,session.getAttribute("custid").toString());
	ps.setString(13,"Booked");
	ps.executeUpdate();

      out.write("\r\n");
      out.write("<h1>Your booking is done successfully.</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
