/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-03 08:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class manage_005fphotographer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"err.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script type='text/javascript'>\r\n");
      out.write("function change(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='1px solid black';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unchange(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='none';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("\tx = document.forms[\"reg\"][\"phone\"];\r\n");
      out.write("\r\n");
      out.write("\tif(!x.value.match(/^\\d{10}$/))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid phone number.\");\r\n");
      out.write("\t\tx.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tx = document.forms[\"reg\"][\"email\"];\r\n");
      out.write("\tif(!x.value.match(/^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid email id.\");\r\n");
      out.write("\t\tx.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event","root","jasper");
	
	String cname = request.getParameter("cname");
	String cpname = request.getParameter("cpname");
	String addr = request.getParameter("addr");
	String phone = request.getParameter("phone");
	String email = request.getParameter("email");
	String rate = request.getParameter("rate");

	PreparedStatement ps = con.prepareStatement("insert into photographer(p_name, p_contact_person, p_address, p_phone, p_email, p_rate) values(?,?,?,?,?,?)");

	if(cname!=null && cpname!=null && addr!=null && phone!=null && email!=null && rate!=null){
		ps.setString(1,cname);
		ps.setString(2,cpname);
		ps.setString(3,addr);
		ps.setString(4,phone);
		ps.setString(5,email);
		ps.setFloat(6,Float.parseFloat(rate));
		ps.executeUpdate();
	}

      out.write("\r\n");
      out.write("<link type='text/css' rel='stylesheet' href='style.css'>\r\n");
      out.write("<article>\r\n");
      out.write("<table width='100%' height='100%' class='admin' style='border-spacing:20px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=4 align='center'>\r\n");
      out.write("\t\t<a href='admin_home.jsp'><img src='images/admin.png' width=200 height=200/></a>\r\n");
      out.write("\t\t<h1>Welcome Admin - ");
      out.print(session.getAttribute("aname"));
      out.write("</h1>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<form method='post' action='manage_photographer.jsp' name='reg' onsubmit='return validate()'>\r\n");
      out.write("\t\t<table width='100%' height='100%' class='admin'>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Photographer Name:</b></td>\r\n");
      out.write("\t\t\t<td><input type='text' name='cname' class='text' required onfocus='change(this)' onblur='unchange(this)'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Contact Person Name:</b></td>\r\n");
      out.write("\t\t\t<td><input type='text' name='cpname' class='text' required onfocus='change(this)' onblur='unchange(this)'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Address:</b></td>\r\n");
      out.write("\t\t\t<td><textarea name='addr' class='text' required onfocus='change(this)' onblur='unchange(this)' rows=5 cols=50></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Phone:</b></td>\r\n");
      out.write("\t\t\t<td><input type='text' name='phone' class='text' required onfocus='change(this)' onblur='unchange(this)'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Email:</b></td>\r\n");
      out.write("\t\t\t<td><input type='text' name='email' class='text' required onfocus='change(this)' onblur='unchange(this)'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Per Day Rate:</b></td>\r\n");
      out.write("\t\t\t<td><input type='text' name='rate' class='text' required onfocus='change(this)' onblur='unchange(this)'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right'><input type='submit' value='ADD' class='btn'></td>\r\n");
      out.write("\t\t\t<td><input type='reset' value='CLEAR' class='btn'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\t\t\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t");

		Statement s = con.createStatement();
		ResultSet rs = s.executeQuery("select * from photographer");
	
      out.write("\r\n");
      out.write("\t<table width='100%' style='background:orange;border:none;font-size:10pt;'>\r\n");
      out.write("\t<tr style='background:red;'>\r\n");
      out.write("\t\t<th>Photographer ID</th>\r\n");
      out.write("\t\t<th>Name</th>\r\n");
      out.write("\t\t<th>Contact</th>\r\n");
      out.write("\t\t<th>Address</th>\r\n");
      out.write("\t\t<th>Phone</th>\r\n");
      out.write("\t\t<th>Email</th>\r\n");
      out.write("\t\t<th>Rate</th>\r\n");
      out.write("\t\t<th colspan=2>Operation</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		while(rs.next()){
	
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'>");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("\t\t<td align='center'><a href='delete_photographer.jsp?cid=");
      out.print(rs.getString(1));
      out.write("' class='opr'>Delete</a></td>\r\n");
      out.write("\t\t<td align='center' style='padding:15px;'><a href='update_photographer.jsp?cid=");
      out.print(rs.getString(1));
      out.write("' class='opr'>Update</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t</table>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</article>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
