/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-04 00:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class manage_005fgallery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"err.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script type='text/javascript'>\r\n");
      out.write("function change(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='1px solid black';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unchange(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='none';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event","root","jasper");
	

      out.write("\r\n");
      out.write("<link type='text/css' rel='stylesheet' href='style.css'>\r\n");
      out.write("<article>\r\n");
      out.write("<table width='100%' height='100%' class='admin' style='border-spacing:20px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=4 align='center'>\r\n");
      out.write("\t\t<a href='admin_home.jsp'><img src='images/admin.png' width=200 height=200/></a>\r\n");
      out.write("\t\t<h1>Welcome Admin - ");
      out.print(session.getAttribute("aname"));
      out.write("</h1>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<form method='post' action='http://localhost:8080/event/gallery' enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<table width='100%' height='100%' class='admin'>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Photo Type:</b></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<select name='ptype' class='text' required onfocus='change(this)' onblur='unchange(this)'>\r\n");
      out.write("\t\t\t<option value=''>Select Gallery Type</option>\r\n");
      out.write("\t\t\t<option value='Party Lawns'>Party Lawns</option>\r\n");
      out.write("\t\t\t<option value='Banquet Hall'>Banquet Hall</option>\r\n");
      out.write("\t\t\t<option value='Catering Services'>Catering Services</option>\r\n");
      out.write("\t\t\t<option value='Flower Decoration'>Flower Decoration</option>\r\n");
      out.write("\t\t\t<option value='Tenting & Decorations'>Tenting & Decorations</option>\r\n");
      out.write("\t\t\t</select>\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right' class='text'><b>Photo:</b></td>\r\n");
      out.write("\t\t\t<td><input type='file' name='photo' required></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align='right'><input type='submit' value='ADD' class='btn'></td>\r\n");
      out.write("\t\t\t<td><input type='reset' value='CLEAR' class='btn'></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\t\t\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t");

		Statement s = con.createStatement();
		ResultSet rs = s.executeQuery("select * from gallery");
		while(rs.next()){
	
      out.write("\r\n");
      out.write("\t<table width='70%' align='center' style='background:orange;border:none;font-size:10pt;'>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align='center'><img src='images/");
      out.print(rs.getString(3));
      out.write("'></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<td align='center'>\r\n");
      out.write("\t\t\t<table style='padding:10px;'>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style='padding:10px;'><b>Gallery ID:</b></td><td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style='padding:10px;'><b>Name:</b></td><td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align='center' colspan=2 style='padding:20px;'><a href='delete_gallery.jsp?vid=");
      out.print(rs.getString(1));
      out.write("' class='opr'>Delete</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table><br>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</article>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
