/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-13 08:18:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class view_005fcust_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"err.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event","root","jasper");
	

	String cid = session.getAttribute("custid").toString();
	PreparedStatement ps = con.prepareStatement("select * from customer where cust_id=?");
	ps.setString(1,cid);
	ResultSet rs = ps.executeQuery();
	rs.next();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("function change(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='1px solid black';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unchange(x)\r\n");
      out.write("{\r\n");
      out.write("\tx.style.border='none';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("\tx = document.forms[\"reg\"][\"pwd\"];\r\n");
      out.write("\ty = document.forms[\"reg\"][\"cpwd\"];\r\n");
      out.write("\r\n");
      out.write("\tif(x.value != y.value)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Password and confirm password doesn't match\");\r\n");
      out.write("\t\tx.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\tx = document.forms[\"reg\"][\"phone\"];\r\n");
      out.write("\r\n");
      out.write("\tif(!x.value.match(/^\\d{10}$/))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid phone number.\");\r\n");
      out.write("\t\tx.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tx = document.forms[\"reg\"][\"email\"];\r\n");
      out.write("\tif(!x.value.match(/^([a-zA-Z0-9_\\.\\-])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid email id.\");\r\n");
      out.write("\t\tx.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link type='text/css' rel='stylesheet' href='style.css'>\r\n");
      out.write("<form method='post' action='edit_cust_profile.jsp' name='reg' onsubmit='return validate()'>\r\n");
      out.write("<table width='100%' height='100%' class='admin'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=2 align='center'><a href='cust_home.jsp'><img src='images/users.jpg' width=300 height=300/></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Customer ID:</b></td>\r\n");
      out.write("\t<td><input type='text' name='cid' class='text' required onfocus='change(this)' onblur='unchange(this)' value='");
      out.print(rs.getString(1));
      out.write("' readOnly></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Customer Password:</b></td>\r\n");
      out.write("\t<td><input type='password' name='pwd' class='text' required onfocus='change(this)' onblur='unchange(this)' value='");
      out.print(rs.getString(2));
      out.write("'></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Name:</b></td>\r\n");
      out.write("\t<td><input type='text' name='name' class='text' required onfocus='change(this)' onblur='unchange(this)' value='");
      out.print(rs.getString(3));
      out.write("'></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Address:</b></td>\r\n");
      out.write("\t<td><textarea name='addr' class='text' required onfocus='change(this)' onblur='unchange(this)' rows=4 cols=50>");
      out.print(rs.getString(4));
      out.write("</textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Phone:</b></td>\r\n");
      out.write("\t<td><input type='text' name='phone' class='text' required onfocus='change(this)' onblur='unchange(this)' value='");
      out.print(rs.getString(5));
      out.write("'></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right' class='text'><b>Email:</b></td>\r\n");
      out.write("\t<td><input type='text' name='email' class='text' required onfocus='change(this)' onblur='unchange(this)' value='");
      out.print(rs.getString(6));
      out.write("'></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td align='right'><input type='submit' value='UPDATE' class='btn'></td>\r\n");
      out.write("\t<td><input type='reset' value='RESET' class='btn'></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
