/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-12-13 21:45:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class view_005fbookings1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"err.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event","root","jasper");
	
	int bno = Integer.parseInt(request.getParameter("bno"));

	PreparedStatement ps = con.prepareStatement("select bill_no, bill_date, cust_name, event_date, occassion, venue_name, decorator_name, caterer_name, p_name, no_of_person, t_name, total_amt from bill, venue, caterer, decorator, photographer, thali, customer where bill.cust_id = customer.cust_id and bill.venue_id = venue.venue_id and bill.p_id = photographer.p_id and bill.t_id = thali.t_id and bill.caterer_id = caterer.caterer_id and bill.decorator_id = decorator.decorator_id and status='Booked' and bill.cust_id=? and bill_no=?");

	ps.setString(1,session.getAttribute("custid").toString());
	ps.setInt(2,bno);

	ResultSet rs = ps.executeQuery();

      out.write("\r\n");
      out.write("<link type='text/css' rel='stylesheet' href='style.css'>\r\n");
      out.write("<form method='post' action='view_bookings1.jsp'>\r\n");
      out.write("<table width='100%' height='100%' class='admin' style='border-spacing:20px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td colspan=4 align='center'>\r\n");
      out.write("\t\t<a href='cust_home.jsp'><img src='images/users.jpg' width=200 height=200/></a>\r\n");
      out.write("\t\t<h1>Welcome Customer - ");
      out.print(session.getAttribute("cname"));
      out.write("</h1>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\t\r\n");
      out.write("\t<td align='center'>\r\n");

	if(rs.next()){

      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr><td><b>Bill No:</b></td><td>");
      out.print(rs.getString(1));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Bill Date:</b></td><td>");
      out.print(rs.getString(2));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Customer:</b></td><td>");
      out.print(rs.getString(3));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Event Date:</b></td><td>");
      out.print(rs.getString(4));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Occassion:</b></td><td>");
      out.print(rs.getString(5));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Venue:</b></td><td>");
      out.print(rs.getString(6));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Decorator:</b></td><td>");
      out.print(rs.getString(7));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Caterer:</b></td><td>");
      out.print(rs.getString(8));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Photographer:</b></td><td>");
      out.print(rs.getString(9));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>No.of Persons:</b></td><td>");
      out.print(rs.getString(10));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Cuisine:</b></td><td>");
      out.print(rs.getString(11));
      out.write("</td></tr>\r\n");
      out.write("\t\t<tr><td><b>Bill Amount:</b></td><td>$.");
      out.print(rs.getString(12));
      out.write("/-</td></tr>\r\n");
      out.write("\t\t</table>\r\n");

	}
	else{

      out.write("\r\n");
      out.write("<h1>Invalid bill no or event date passed or bill already canceled.</h1>\r\n");

	}

      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
